openapi: 3.0.3
info:
  title: WASAText
  description: |
    API for the WASAText application, which is the project for the WASA course @ Sapienza
  version: 0.0.1

components:
  schemas:
    User:
      $ref: "./schemas/user.yaml"

    Message:
      $ref: "./schemas/message.yaml"

    Reaction:
      $ref: "./schemas/reaction.yaml"

    Chat:
      $ref: "./schemas/chat.yaml"
  

paths:
  /session:
    # POST = doLogin
    $ref: "./paths/session.yaml"
  
  /session/{id}/chats:
    # POST = getMyConversations
    $ref: "./paths/user-chats.yaml"
  
  /session/{id}/name:
    # POST = setMyUserName
    $ref: "./paths/user-name.yaml"

  /session/{id}/photo:
    # POST = setMyPhoto
    $ref: "./paths/user-photo.yaml"

  /session/{id}/bio:
    # POST = setMyBio
    $ref: "./paths/user-bio.yaml"

  /session/{id}/{chatID}:
    # GET = getConversation
    $ref: "./paths/chat-get-by-id.yaml"

  /session/{id}/{chatID}/people:
    # PUT = addToGroup
    # POST = leaveGroup
    $ref: "./paths/chat-add-leave.yaml"

  /session/{id}/{chatID}/name:
    # POST = setGroupName
    $ref: "./paths/chat-name.yaml"

  /session/{id}/{chatID}/photo:
    # POST = setGroupPhoto
    $ref: "./paths/chat-photo.yaml"

  /session/{id}/{chatID}/description:
    # POST = setGroupDescription
    $ref: "./paths/chat-description.yaml"

  /session/{id}/{chatID}/{messageID}:
    # POST = sendMessage
    # DELETE = deleteMessage
    $ref: "./paths/message-send-delete.yaml"

  /session/{id}/{chatID}/{messageID}/{commentID}:
    # POST = commentMessage
    # DELETE = uncommentMessage
    $ref: "./paths/message-comment-uncomment.yaml"

  /session/{id}/{chatID}/{messageID}/forward:
    # POST = forwardMessage
    $ref: "./paths/messages.yaml"