openapi: 3.0.3
info:
  title: WASAText
  description: |
    API for the WASAText application, which is the project for the WASA course @ Sapienza
  version: 0.0.1

components:
  schemas:
    user:
      $ref: "./schemas/user.yaml"

    message:
      $ref: "./schemas/message.yaml"

    reaction:
      $ref: "./schemas/reaction.yaml"

    chat:
      $ref: "./schemas/chat.yaml"
  

paths:
  /session:
    # POST = doLogin
    $ref: "./paths/session.yaml"
  
  /session/{id}/chats:
    # POST = getMyConversations
    $ref: "./paths/user-chats.yaml"

  /chat/{id}:
    # GET = getConversation
    $ref: "./paths/session-id.yaml"

  /user/{id}/name:
    # POST = setMyUserName
    $ref: "./paths/user-name.yaml"